//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Monitor.Service
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MonitorData", Namespace="http://schemas.datacontract.org/2004/07/Core.Monitor.Service")]
    public partial class MonitorData : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string OperationNameField;
        
        private string TraceMessageField;
        
        private short TracePointField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationName
        {
            get
            {
                return this.OperationNameField;
            }
            set
            {
                this.OperationNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TraceMessage
        {
            get
            {
                return this.TraceMessageField;
            }
            set
            {
                this.TraceMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short TracePoint
        {
            get
            {
                return this.TracePointField;
            }
            set
            {
                this.TracePointField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="MonitorContract")]
public interface MonitorContract
{
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/MonitorContract/TraceInformation")]
    void TraceInformation(Core.Monitor.Service.MonitorData data);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/MonitorContract/TraceInformation")]
    System.Threading.Tasks.Task TraceInformationAsync(Core.Monitor.Service.MonitorData data);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/MonitorContract/TraceWarning")]
    void TraceWarning(Core.Monitor.Service.MonitorData data);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/MonitorContract/TraceWarning")]
    System.Threading.Tasks.Task TraceWarningAsync(Core.Monitor.Service.MonitorData data);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/MonitorContract/TraceError")]
    void TraceError(Core.Monitor.Service.MonitorData data);
    
    [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/MonitorContract/TraceError")]
    System.Threading.Tasks.Task TraceErrorAsync(Core.Monitor.Service.MonitorData data);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface MonitorContractChannel : MonitorContract, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MonitorContractClient : System.ServiceModel.ClientBase<MonitorContract>, MonitorContract
{
    
    public MonitorContractClient()
    {
    }
    private bool _traceInformation;
    public MonitorContractClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }

    public MonitorContractClient(System.ServiceModel.Channels.Binding binding, bool traceInformation, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
            _traceInformation = traceInformation;
    }
    public MonitorContractClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MonitorContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MonitorContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void TraceInformation(Core.Monitor.Service.MonitorData data)
    {
        base.Channel.TraceInformation(data);
    }
    
    public System.Threading.Tasks.Task TraceInformationAsync(Core.Monitor.Service.MonitorData data)
    {
        return base.Channel.TraceInformationAsync(data);
    }
    
    public void TraceWarning(Core.Monitor.Service.MonitorData data)
    {
        base.Channel.TraceWarning(data);
    }
    
    public System.Threading.Tasks.Task TraceWarningAsync(Core.Monitor.Service.MonitorData data)
    {
        return base.Channel.TraceWarningAsync(data);
    }
    
    public void TraceError(Core.Monitor.Service.MonitorData data)
    {
        base.Channel.TraceError(data);
    }
    
    public System.Threading.Tasks.Task TraceErrorAsync(Core.Monitor.Service.MonitorData data)
    {
        return base.Channel.TraceErrorAsync(data);
    }
}
